apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-api
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/giriraj7singh-code/aws-devops-gitops-project.git
    targetRevision: main
    path: kubernetes

  destination:
    server: https://kubernetes.default.svc
    namespace: devops

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
